feat: взаимодействие с БД с помощью Hibernate
almariel4/java-shareit pull request #2
Opened 2023-06-18 22:40 UTC by almariel4

2023-06-19 17:04 UTC, mikita95 requested changes
Все сделано просто отлично. Оставил лишь небольшие замечания

2023-06-19 17:04 UTC, mikita95 commented on src/main/resources/schema.sql
> +  status status,
Статус не может быть null

2023-06-19 17:04 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    public UserDto getUser(@PathVariable("userId") Long userId) {
Можно использовать примитивный long как userId, он обязательный

2023-06-19 17:04 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> +    public UserDto updateUser(@PathVariable("userId") Long userId, @Valid @RequestBody UserDto userDto) {
Можно использовать примитивный long как userId, он обязательный

2023-06-19 17:04 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@Data
Лучше не использовать аннотацию lombok Data с сущностями hibernate. Проблема в том, что так сгенерируются методы equals(), hashCode() и toString(), которые если используются lazy или циклические зависимости между сущностями все поломают. Лучше определить их руками, если нужно, так можно избежать ошибок в будущем

2023-06-19 17:04 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +    public BookingDto addBooking(Long userId, BookingDto bookingDto) {
Лучше использовать транзакции (аннотация Transactional), так при параллельном исполнении запросов, база данных останется в консистентном состоянии.
Для методов, где проиходит только чтения, стоит использовать флаг readOnly

2023-06-19 17:04 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/user/service/UserService.java
> +@Service
Над интерфейсом не нужно добавлять аннотацию спринга

2023-06-19 19:43 UTC, almariel4 commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@Data
Почему поломают?

2023-06-20 13:04 UTC, mikita95 commented on src/main/java/ru/practicum/shareit/item/model/Comment.java
> +@Data
Например, если сущность содержит lazy-поля, то они все равно добавятся в реализации этих методов. И каждый раз при их вызове будет происходить обращение в базу данных, что может понизить производительность приложения. Поэтому стоит руками точно указать реалиции методов equals(), hashCode() и toString(). Также если, например, классы A и B содержат ссылки друг на друга (например, отношение many-to-many), то при вызове метода toString на одном из них можно получить StackOverflowError, так как получится цикл.

2023-06-20 17:28 UTC, mikita95 approved these changes
Все сделано хорошо. Можно мержить пул-реквест

2023-06-20 19:19 UTC, merged